const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require('fs');
const path = require('path');
const { createDocx } = require('../models/reportModel');

const generateReportService = async (topic, pages) => {
  try {
    const apiKey = process.env.GOOGLE_API_KEY;
    const genAI = new GoogleGenerativeAI(apiKey);

    // Initialize the model
    const model = await genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    // Define the prompt
    const prompt = `Generate a report on ${topic} with ${pages} pages.`;

    // Generate content using the model
    const result = await model.generateContent([prompt ]);

    // Check if the response contains the generated text
    if (result && result.response && typeof result.response.text === 'function') {
      const reportContent = result.response.text();

      // Save the report content to a DOCX file
      const reportPath = createDocx(reportContent);

      return reportPath;
    } else {
      throw new Error('No content was generated by the model.');
    }
  } catch (error) {
    console.error('Error generating report:', error);
    throw error;
  }
};

module.exports = {
  generateReportService,
};
